=== Jyotishukla/Services-Oriented-Architecture/assignment01/dtd/transactions.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT transactions (transaction)+>

<!ELEMENT transaction (transaction_id, order_id, price_id, transaction_date, transaction_description, transaction_amount, make, model, year, employee_id, truck_no, discount, quantity, unit_price, driver_price, vin, run_number, special, rate, surcharge ) >

<!ELEMENT transaction_id (#PCDATA)>
<!ELEMENT order_id (#PCDATA)>
<!ELEMENT price_id (#PCDATA)>
<!ELEMENT transaction_date (#PCDATA)>
<!ELEMENT transaction_description (#PCDATA)>
<!ELEMENT transaction_amount (#PCDATA)>
<!ELEMENT make (#PCDATA)>
<!ELEMENT  model(#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT employee_id (#PCDATA)>
<!ELEMENT truck_no (#PCDATA)>
<!ELEMENT discount (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT unit_price (#PCDATA)>
<!ELEMENT driver_price (#PCDATA)>
<!ELEMENT vin (#PCDATA)>
<!ELEMENT run_number (#PCDATA)>
<!ELEMENT special (#PCDATA)>
<!ELEMENT rate (#PCDATA)>
<!ELEMENT surcharge (#PCDATA)>

=== Jyotishukla/Services-Oriented-Architecture/xmls/Transactions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE transactions SYSTEM "transactions.dtd">
<transactions>
	<transaction>
		<transaction_id></transaction_id>
		<order_id></order_id>
		<price_id></price_id>
		<transaction_date></transaction_date>
		<transaction_description></transaction_description>
		<transaction_amount></transaction_amount>
		<make></make>
		<model></model>
		<year></year>
		<employee_id></employee_id>
		<truck_no></truck_no>
		<discount></discount>
		<quality></quality>
		<unit_price></unit_price>
		<driver_pric></driver_pric>
		<vin></vin>
		<run_number></run_number>
		<special></special>
		<rate></rate>
		<special></special>
		<rate></rate>
		<surcharge></surcharge>
	</transaction>
</transactions>
