=== Jyotishukla/Services-Oriented-Architecture/Assignment_01_soa/dtd/customers.dtd
<!ELEMENT customers (customer)+>

<!ELEMENT customer (customer_id, customer_title, business_name, billing_address, city, state, postal_code,country, phone_number,  cell_number, other_number, fax_number,email_address, customer_type, company_name, contact_name, alternate_contact_name, date_entered) >

<!ELEMENT customer_id (#PCDATA)>
<!ELEMENT customer_title (#PCDATA) >
<!ELEMENT business_name (#PCDATA) >
<!ELEMENT billing_address (#PCDATA) >
<!ELEMENT  city (#PCDATA) >
<!ELEMENT state (#PCDATA) >
<!ELEMENT postal_code (#PCDATA) >
<!ELEMENT country (#PCDATA) >
<!ELEMENT phone_number (#PCDATA) >
<!ELEMENT cell_number (#PCDATA) >
<!ELEMENT other_number (#PCDATA) >
<!ELEMENT fax_number (#PCDATA) >
<!ELEMENT email_address (#PCDATA) >
<!ELEMENT customer_type (#PCDATA) >
<!ELEMENT company_name (#PCDATA) >
<!ELEMENT contact_name (#PCDATA) >
<!ELEMENT alternate_contact_name (#PCDATA) >
<!ELEMENT date_entered (#PCDATA) >

=== Jyotishukla/Services-Oriented-Architecture/assignment01/xmls/Customer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE customers SYSTEM "customers.dtd">
<customers>
	<customer>
		<customer_id></customer_id>
		<customer_title></customer_title>
		<buisness_name></buisness_name>
		<billing_address></billing_address>
		<city></city>
		<state></state>
		<postal_code></postal_code>
		<country></country>
		<phone_no></phone_no>
		<cell_number></cell_number>
		<other_number></other_number>
		<fax_number></fax_number>
		<email_address></email_address>
		<customer_type></customer_type>
		<company_type></company_type>
		<contact_name></contact_name>
		<alternate_contactname></alternate_contactname>
		<date_entered></date_entered>
	</customer>
</customers>
