=== Jyotishukla/Services-Oriented-Architecture/Assignment_01_soa/dtd/employees.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT employees  (employee)+>

<!ELEMENT employee (employee_id , first_name, last_name, email, extension, home_phone , cell_phone, jobtitle, ssn , driver_license_number , address , city , state , postal_code , birth_date, date_hired , salary , notes )>

<!ELEMENT employee_id (#PCDATA)>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT extension (#PCDATA)>
<!ELEMENT home_phone (#PCDATA)>
<!ELEMENT cell_phone (#PCDATA)>
<!ELEMENT jobtitle (#PCDATA)>
<!ELEMENT ssn (#PCDATA)>
<!ELEMENT driver_license_number (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT postal_code (#PCDATA)>
<!ELEMENT birth_date (#PCDATA)>
<!ELEMENT date_hired (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ELEMENT notes (#PCDATA)>

=== Jyotishukla/Services-Oriented-Architecture/assignment01/xmls/Employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "employees.dtd">
<employees>
	<employee>
		<employee_id></employee_id>
		<first_name></first_name>
		<last_name></last_name>
		<email></email>
		<extension></extension>
		<home_phone></home_phone>
		<cell_phone></cell_phone>
		<jobtitle></jobtitle>
		<ssn></ssn>
		<driver_license_number></driver_license_number>
		<address></address>
		<city></city>
		<state></state>
		<postal_code></postal_code>
		<birth_date></birth_date>
		<date_hired></date_hired>
		<salary></salary>
		<notes></notes>
	</employee>
</employees>
